### ISSUE TITLE
1.4.1 高斯消元法基本步骤中唯一解判断条件不充分

### ISSUE THREAD

**Issue by Williamdepig** [yhwu-is/Linear-Algebra-for-ZJUCKC#15]
原文是：
<img width="676" alt="高斯消元法" src="https://github.com/yhwu-is/Linear-Algebra-for-ZJUCKC/assets/111695841/ffb6f6f8-49ce-4167-97c7-3235dfa2a316">
判断有唯一解时，还应增加条件：**末位主元素的行号r与系数矩阵的列数n相等**.

教材对照:
<img width="407" alt="教材" src="https://github.com/yhwu-is/Linear-Algebra-for-ZJUCKC/assets/111695841/f7daa2a2-1135-49a0-a091-5dc90e28eb00">

**Comment by yhwu-is** [comment]
感觉我这里的表应该和书上是等价的？

**Comment by Williamdepig** [comment]
问题可能出现在不同人对对角线的认知不同，如果就认为对角线是行数与列数相等的元素，那么当列数n大于行数m时，若仅对角线元素为1，其余元素均为0，则从第m+1到第n的未知数就有无穷多解了.

**Comment by yhwu-is** [comment]
主要还有没全零行这句话来着

**Comment by yhwu-is** [comment]
谢谢，下次更新第一讲正文更正
